# docker-compose.yml

version: '3.9'

services:
  web:
    build: .
    command: python run.py
    volumes:
      - .:/app
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres_user:postgres_pass@db:5432/postgres
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    command: -c max_connections=200 -c ssl=yes -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./server.crt:/var/lib/postgresql/server.crt
      - ./server.key:/var/lib/postgresql/server.key
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_DB=postgres
volumes:
  postgres_data:
