name: fastapi-sqlalchemy-doapp
services:
- environment_slug: python-3.8.6
  github:
    branch: main
    deploy_on_push: true
    repo: justinrmiller/fastapi-sqlalchemy-doapp
  name: fastapi-sqlalchemy-doapp
