name: fastapi-sqlalchemy-doapp
databases:
- engine: PG
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: justinrmiller/fastapi-sqlalchemy-doapp
  name: fastapi-sqlalchemy-doapp
  health_check:
    initial_delay_seconds: 10
    period_seconds: 3
    timeout_seconds: 5
    success_threshold: 3
    failure_threshold: 5
    http_path: /healthcheck
