name: fastapi-sqlalchemy-digitaloceanapps
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: justinrmiller/fastapi-sqlalchemy-digitaloceanapps
  name: fastapi-sqlalchemy-digitaloceanapps
